### ISSUE TITLE
Does it work on Korean servers?

### ISSUE THREAD

**Issue by YankeeTube** [Zageku/DNF_pvf_python#10]
I needed a script.pvf reading code so I came all the way here! 

It's really good code

But it's not easy to analyze because it's mainly written in the Chinese version and GUI
Is it possible to use a Korean server? I'd like to get help if possible

**Comment by Zageku** [comment]
It can be used on the leaked version of the Taiwanese server and its modified version.
Cannot read the official pvf file of the current Korean server.

**Comment by YankeeTube** [comment]
> It can be used on the leaked version of the Taiwanese server and its modified version. Cannot read the official pvf file of the current Korean server.

Thank you for your quick reply!

Why can't you read it? Is it because the structure is different from other countries?

**Comment by Zageku** [comment]
Different versions use different keys for encryption, and may even have different encryption methods.
Officials are also using various methods to prevent players from cracking data.

**Comment by YankeeTube** [comment]
> Different versions use different keys for encryption, and may even have different encryption methods. Officials are also using various methods to prevent players from cracking data.

Thank you for your kind reply That really helped me a lot! I'll close the issue!
